spring:
  application:
    name: api-gateway-core    # 应用名称，用于服务注册与发现
  data:
    redis: # Redis数据库配置（用于存储接口信息）
      database: 0             # Redis数据库索引（0-15）
      host: 192.168.74.32         # Redis服务器地址
      port: 6379             # Redis服务器端口

# API网关核心配置
api-gateway:
  netty-port: 8888           # Netty服务监听端口
  gateway-center: 127.0.0.1:18080  # 网关中心地址（用于配置同步）
  group-key: test-key         # 网关分组标识（用于启动时获取配置）
  weight: 1                   # 网关权重（1-100，用于负载均衡）
  max-cache: 1000             # 连接对象本地缓存最大数量
  boss-threads: 1             # Netty boss线程数（接收连接）
  worker-threads: 4           # Netty worker线程数（处理连接）

# Dubbo配置
dubbo:
  application:
    qos-enable: false         # 是否启用Dubbo QOS服务（运维命令）